version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
